[package]
authors = ["steinuil <steenuil.owl@gmail.com>"]
edition = "2018"
name = "get_keys"
version = "1.0.0"

[dependencies]
clap = "3.0.0-beta.2"
egg-mode = {git = "https://github.com/egg-mode-rs/egg-mode", rev = "6b81073eba9"}
tokio = {version = "1.8", features = ["full"]}
webbrowser = "0.5"
